spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/CAR_SERVICE
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
